name: themoviesapp
description: A movies collection cum inventory app built with Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.2
  flutter_bloc: ^6.0.1
  rxdart: ^0.24.1
  cached_network_image: ^2.2.0+1

flutter:

  uses-material-design: true

  assets:
    - assets/images/movie-posters/
    - assets/images/actor-posters/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700